In [7]:
%pip install pandas

Requirement already satisfied: pandas in /Users/estergracia/miniconda3/lib/python3.9/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd

In [9]:
ANIME_CSV_PATH = 'mal_anime.csv'
CHAR_CSV_PATH = 'mal_characters_detailed.csv'

In [10]:
df_anime = pd.read_csv(ANIME_CSV_PATH)
df_characters = pd.read_csv(CHAR_CSV_PATH)

# Preprocess Anime

In [11]:
df_anime.head()

,myanimelist_id,title,description,image,Type,Episodes,Status,Premiered,Released_Season,Released_Year,...,Demographic,Duration,Rating,Score,Ranked,Popularity,Members,Favorites,characters,source_url
0,1,Cowboy Bebop,"Crime is timeless. By the year 2071, humanity ...",https://cdn.myanimelist.net/images/anime/4/196...,TV,26,Finished Airing,Spring 1998,Spring,1998.0,...,NaN,24 min. per ep.,R - 17+ (violence & profanity),8.75,#48,#42,"2,008,019","87,916","[{""id"": 3, ""name"": ""Black, Jet"", ""url"": ""https...",https://myanimelist.net/anime/1/Cowboy_Bebop
1,5,Cowboy Bebop: Tengoku no Tobira,"Another day, another bounty—such is the life o...",https://cdn.myanimelist.net/images/anime/1439/...,Movie,1.0,Finished Airing,NaN,NaN,NaN,...,NaN,1 hr. 55 min.,R - 17+ (violence & profanity),8.38,#232,#649,"403,604","1,748","[{""id"": 3, ""name"": ""Black, Jet"", ""url"": ""https...",https://myanimelist.net/anime/5/Cowboy_Bebop__...
2,6,Trigun,"Vash the Stampede is the man with a $$60,000,0...",https://cdn.myanimelist.net/images/anime/1130/...,TV,26,Finished Airing,Spring 1998,Spring,1998.0,...,Shounen,24 min. per ep.,PG-13 - Teens 13 or older,8.22,#385,#265,"815,140","17,193","[{""id"": 713, ""name"": ""Stryfe, Meryl"", ""url"": ""...",https://myanimelist.net/anime/6/Trigun
3,7,Witch Hunter Robin,"Though hidden away from the general public, Wi...",https://cdn.myanimelist.net/images/anime/10/19...,TV,26.0,Finished Airing,Summer 2002,Summer,2002.0,...,NaN,25 min. per ep.,PG-13 - Teens 13 or older,7.23,#3344,#1979,"125,868",686,"[{""id"": 300, ""name"": ""Amon"", ""url"": ""https://m...",https://myanimelist.net/anime/7/Witch_Hunter_R...
4,8,Bouken Ou Beet,It is the dark century and the people are suff...,https://cdn.myanimelist.net/images/anime/7/215...,TV,52,Finished Airing,Fall 2004,Fall,2004.0,...,Shounen,23 min. per ep.,PG - Children,6.92,#4887,#5765,"16,456",18,"[{""id"": 9054, ""name"": ""Beet"", ""url"": ""https://...",https://myanimelist.net/anime/8/Bouken_Ou_Beet

In [12]:
df_characters = pd.read_csv(CHAR_CSV_PATH)

In [13]:
import json

def parse_character_attributes(attributes_str):
    parsed_attrs = {}
    if pd.notna(attributes_str):
        try:
            attributes_list = json.loads(attributes_str)
            if isinstance(attributes_list, list):
                for attr_dict in attributes_list:
                    if isinstance(attr_dict, dict) and 'name' in attr_dict and 'value' in attr_dict:
                        parsed_attrs[attr_dict['name']] = attr_dict['value']
        except json.JSONDecodeError:
            # Malformed JSON, return empty dictionary
            return {}
    return parsed_attrs

df_characters['parsed_attributes_dict'] = df_characters['attributes'].apply(parse_character_attributes)

print("New column 'parsed_attributes_dict' created with extracted attributes.")
display(df_characters[['full_name', 'attributes', 'parsed_attributes_dict']].head())

New column 'parsed_attributes_dict' created with extracted attributes.

,full_name,attributes,parsed_attributes_dict
0,Spike Spiegel,"[{""name"": ""Birthdate"", ""value"": ""June 26, 2044...","{'Birthdate': 'June 26, 2044', 'Height': '185 ..."
1,Faye Valentine,"[{""name"": ""Birthday"", ""value"": ""August 14, 199...","{'Birthday': 'August 14, 1994'}"
2,Jet Black,NaN,{}
3,Ein,NaN,{}
4,Ichigo Kurosaki,"[{""name"": ""Race"", ""value"": ""Human Quincy, Holl...","{'Race': 'Human Quincy, Hollow', 'Birthday': '..."

In [14]:
false_positive = ['Age', 'Background', 'Personality', 'Comments', 'Known relatives', 'Famous quote', 'Subjects she is good at', 'Ability parameters (out of 5)', 'Ability Parameters (out of 5):', '(Anime) Drive to Duel', 'Experience with playing musical instruments', "Unique Skill - Demon Wolf's KingResistance", 'Things he doesn’t like', 
                  'Would Like to Hide', 'Hobby and Special Skills', 'How he spends days off', 'Favorite type of girl', 'Spends his allowance on', 'Most visited spot in the school',
                  'Most frequented spot in school', 'Experience with Playing Musical Instruments', 'Special skill aside from tennis', 'Pet she wants to raise', 
                  'What he wants most at the moment', 'Rikkaidai Fuzoku Middle School', 'Favorite type of books', "Doesn't like/bad at doing", "Things I'm not good at", "Way to pass time when alone"]
for index, row in df_characters.iterrows():
    attributes_dict = row['parsed_attributes_dict']

    if pd.notna(attributes_dict):
        try:
            # Iterate over a copy of the dictionary items to avoid RuntimeError
            for key, value in list(attributes_dict.items()):
                if key in false_positive:
                  continue
                full_str = key + ": " + value
                if (len(key.split()) > 3) and (len(full_str.split())>9):
                  print(full_str)
                  print()
                  # Ensure description is a string before concatenation
                  current_description = df_characters.loc[index, 'description']
                  if pd.isna(current_description):
                      df_characters.loc[index, 'description'] = full_str
                  else:
                      df_characters.loc[index, 'description'] = full_str + current_description
                  df_characters.loc[index, 'parsed_attributes_dict'].pop(key)
        except json.JSONDecodeError:
            # Skip entries that are not valid JSON
            continue

A youkai who is Sesshoumaru's servant: not especially powerful but extremely loyal, he is usually a comical character. Sesshoumaru typically responds to Jaken's failures or more annoying behavior with a sound beating, but Jaken believes this is Sesshomaru's right and never wavers in his loyalty. Jaken started following him in the first place after being captivated by his power and majesty when he slayed a threatening demon, saving Jaken's life (this was incidental; Sesshomaru killed the demon simply because it was in his way. Note: these events were related ONLY in the anime). ("Jaken" means "meanness" or "unkindness".)

The main human character of the series: a pink-haired, red-eyed, 16-year-old, high school student obsessed with mysteries and the occult. Despite her love of strange cases, she never manages to find out who Loki is-- partly due to the fact that she has absolutely no sixth sense, despite being the daughter of a Shinto priest.

It's all in the name with Vicious: he is ruthless, bloodthirsty, cunning and ambitious, willing to do anything in order to secure a position of power. He is a member of the Red Dragon Crime Syndicate in Tharsis, and is often referred to or depicted as a venomous snake. His weapon of choice is not a firearm, but a katana which he wields skillfully, even against gun-wielders. After Spike's supposed death, Vicious also leaves the Red Dragons briefly to fight in the Titan War of 2068 although his precise motivations for enlisting are debated.

Kagura's name comes from Shinto ritual: the kanji for Kagura (神楽) meaning "entertainment of the gods". It was used to describe the traditional music played at shrines and the Imperial Court. Kagura also makes a cameo appearance as an anthropologist in Classroom of Thesis; From the Report to the Graduation Thesis by Kazuhisa Todayama which refers to several other Azumanga Daioh characters.

Konohamaru named after the village he lives in: Konoha, is the grandson of the Third Hokage and by extension the nephew of Asuma Sarutobi. Konohamaru usually hangs out with his two friends, Udon and Moegi. Together, they call themselves the "Konohamaru Corps" ("Konohamaru Ninja Squad" in the English dub). In Part II they are teamed together under the leadership of Ebisu, Konohamaru's former tutor.

Morrison is a character in Devil May Cry: The Animated Series who brings Dante most of his job requests, much like Enzo did previously. However, unlike Enzo, Morrison is calm and doesn't get very scared by the demons that Dante hunts, as shown in the final mission of the anime. Morrison is also shown to be a handyman of sorts when Patty asks him to fix the TV in Dante's office. Like Lady, Dante owes Morrison a sum of money although how much is never really implied, although he continues to bring Dante jobs even with a lack of confidence he will ever be paid, no matter how many good jobs he brings Dante.

The antagonist of Final Fantasy: Legend of the Crystals is Ra Devil, a powerful wizard intent on gaining the power of the Void for his own ambition. He steals Cid's brain away in hopes of using its knowledge of the four Crystals to his advantage, assuming his true form, Deathgyunos, once he succeeds.

Section 2 Division 2 Team 1: The bubbly, perky, red-headed labor otaku from Hokkaidou. The main character of the show, Noa is usually the one at the center of the action. Noa loves her labor much like a pet and named it "Alphonse", a name previously held by a pet dog and a pet cat she had while growing up. She's impulsive and doesn't think things through, but not nearly as much as Ohta. Noa is arguably the best pilot in Division 2, although both Clancy and Kumagami have shown extreme talent as well but rarely pilot. She has a natural affinity for labors and gets 110% out of it, much to her partner's amazement. She can drink quite a bit more than her coworkers, and recovers from hangovers much faster since her family runs a liquor store.

Jonathan Joestar is the protagonist of Part 1: Phantom Blood, and the first JoJo of the JoJo's Bizarre Adventure series. The son of George Joestar I, Jonathan is an honest, kind, and positive man whose life is fraught with tragedy after meeting his adopted older brother, Dio Brando.

Morrison is a character in Devil May Cry: The Animated Series who brings Dante most of his job requests, much like Enzo did previously. However, unlike Enzo, Morrison is calm and doesn't get very scared by the demons that Dante hunts, as shown in the final mission of the anime. Morrison is also shown to be a handyman of sorts when Patty asks him to fix the TV in Dante's office. Like Lady, Dante owes Morrison a sum of money although how much is never really implied, although he continues to bring Dante jobs even with a lack of confidence he will ever be paid, no matter how many good jobs he brings Dante.

The antagonist of Final Fantasy: Legend of the Crystals is Ra Devil, a powerful wizard intent on gaining the power of the Void for his own ambition. He steals Cid's brain away in hopes of using its knowledge of the four Crystals to his advantage, assuming his true form, Deathgyunos, once he succeeds.

Section 2 Division 2 Team 1: The bubbly, perky, red-headed labor otaku from Hokkaidou. The main character of the show, Noa is usually the one at the center of the action. Noa loves her labor much like a pet and named it "Alphonse", a name previously held by a pet dog and a pet cat she had while growing up. She's impulsive and doesn't think things through, but not nearly as much as Ohta. Noa is arguably the best pilot in Division 2, although both Clancy and Kumagami have shown extreme talent as well but rarely pilot. She has a natural affinity for labors and gets 110% out of it, much to her partner's amazement. She can drink quite a bit more than her coworkers, and recovers from hangovers much faster since her family runs a liquor store.

Jonathan Joestar is the protagonist of Part 1: Phantom Blood, and the first JoJo of the JoJo's Bizarre Adventure series. The son of George Joestar I, Jonathan is an honest, kind, and positive man whose life is fraught with tragedy after meeting his adopted older brother, Dio Brando.

The main antagonist in the movie Dragon Ball Z: Fusion Reborn.

The Japanese-produced Night Warriors: Darkstalker's Revenge anime featured Morrigan more like her game appearances, portraying her as a semi-innocent demon world inhabitant, a member of the royal family who was more interested in going to Earth than in her duties. The picture of idle rich, she would often leave at will out of mere boredom, much to the frustration of her guardians, elder men of the Aensland family. Morrigan's role as a hero was a focus, with her activities as a succubus downplayed; although the OVA depicts Donovan Baine as the main hero of the story, some say that Morrigan was also a little more stoic and pretentious than her usually upbeat personality depicted in the games. She is also shown fighting Jon Talbain in the episode intros for the first three episodes.

NYPD, Section 2 Division 2 Team 2: A temporary member of Section 2, on assignment from the NYPD. Sent to observe a labor unit with the purpose of helping build one for New York City. Highly capable in all duties. Her piloting skills are better than Ohta's, but was assigned to backup duty since acclimating the Labor to a temporary officer would be a poor decision. (Also, keeping Ohta in line is not a job for an idiot). Much like Nagumo, Kanuka is very by-the-book. She is usually all business and sometimes cold to the members of SV.2 with the exception of Noa. Kanuka was born in Hawaii but apparently moved to New York later on. When she travels back to New York, she stops in Hawaii to see her grandmother whom she loves dearly. Kanuka's piloting skills are to be feared. Goto certainly thinks so, since he called her in to assist SV2 in the first movie.

Toki Mishiba (美 柴鴇, Mishiba Toki) Voiced by: Suzumura Kenichi

Kazuo Saitoh (斉藤 一雄, Saitō Kazuo?) Voiced by: Hiroki Takahashi

The Tower Tycoon Palmer (Japanese: タワータイクーン クロツグ Tower Tycoon Kurotsugu) is the leader of the Battle Tower in Pokémon Diamond and Pearl. He is Pearl's father. He is very similar to his son in look and character, as he's always in a rush. He is probably a good friend of the unknown father of the player character. Just like the player and his rival did, he also got to a lake with the player's father and was also attacked by wild Pokémon.

Takumi is the main character of the series: Chaos;Head. He is a hikikomori and only attends school in order to fulfill the minimum for graduation requirements. He often and repeatedly notes that he is not interested in girls in the three-dimensional world and avoids conversations with others whenever possible. He prefers to engage in watching anime, playing eroge, and massively multiplayer online role-playing games. He is a second-year student at Suimei Academy (翠明学園, Suimei Gakuen).

Cidre is one of the "Double Mermaids": if she cries tears of sadness they are regular tears, but if she cries tears of happiness her tears turns into crystals. She appears in episode 1.

Kuronue was first seen in the Yu Yu Hakusho movie: Poltergeist Report.  Kurama recodnised him from the past as his partner while thieving.  During the theft of a mirror, a bamboo spear pierced through the bat demon's favorite necklace which appears to be made of ruby and gold.  Despite Youko's cry of protest Kuronue went back after it and was pierced through the major arteries with bamboo spears, utterly ending his life.  While Kurama is now a member of the party of Yusuke.  A demon disguised as Kuronue attacks Kurama while he is alone.

All information found in the movie, Yu Yu Hakusho: Poltergeist Report.

The main antagonist in the movie Dragon Ball Z: Fusion Reborn.

The Japanese-produced Night Warriors: Darkstalker's Revenge anime featured Morrigan more like her game appearances, portraying her as a semi-innocent demon world inhabitant, a member of the royal family who was more interested in going to Earth than in her duties. The picture of idle rich, she would often leave at will out of mere boredom, much to the frustration of her guardians, elder men of the Aensland family. Morrigan's role as a hero was a focus, with her activities as a succubus downplayed; although the OVA depicts Donovan Baine as the main hero of the story, some say that Morrigan was also a little more stoic and pretentious than her usually upbeat personality depicted in the games. She is also shown fighting Jon Talbain in the episode intros for the first three episodes.

NYPD, Section 2 Division 2 Team 2: A temporary member of Section 2, on assignment from the NYPD. Sent to observe a labor unit with the purpose of helping build one for New York City. Highly capable in all duties. Her piloting skills are better than Ohta's, but was assigned to backup duty since acclimating the Labor to a temporary officer would be a poor decision. (Also, keeping Ohta in line is not a job for an idiot). Much like Nagumo, Kanuka is very by-the-book. She is usually all business and sometimes cold to the members of SV.2 with the exception of Noa. Kanuka was born in Hawaii but apparently moved to New York later on. When she travels back to New York, she stops in Hawaii to see her grandmother whom she loves dearly. Kanuka's piloting skills are to be feared. Goto certainly thinks so, since he called her in to assist SV2 in the first movie.

Toki Mishiba (美 柴鴇, Mishiba Toki) Voiced by: Suzumura Kenichi

Kazuo Saitoh (斉藤 一雄, Saitō Kazuo?) Voiced by: Hiroki Takahashi

The Tower Tycoon Palmer (Japanese: タワータイクーン クロツグ Tower Tycoon Kurotsugu) is the leader of the Battle Tower in Pokémon Diamond and Pearl. He is Pearl's father. He is very similar to his son in look and character, as he's always in a rush. He is probably a good friend of the unknown father of the player character. Just like the player and his rival did, he also got to a lake with the player's father and was also attacked by wild Pokémon.

Takumi is the main character of the series: Chaos;Head. He is a hikikomori and only attends school in order to fulfill the minimum for graduation requirements. He often and repeatedly notes that he is not interested in girls in the three-dimensional world and avoids conversations with others whenever possible. He prefers to engage in watching anime, playing eroge, and massively multiplayer online role-playing games. He is a second-year student at Suimei Academy (翠明学園, Suimei Gakuen).

Cidre is one of the "Double Mermaids": if she cries tears of sadness they are regular tears, but if she cries tears of happiness her tears turns into crystals. She appears in episode 1.

Kuronue was first seen in the Yu Yu Hakusho movie: Poltergeist Report.  Kurama recodnised him from the past as his partner while thieving.  During the theft of a mirror, a bamboo spear pierced through the bat demon's favorite necklace which appears to be made of ruby and gold.  Despite Youko's cry of protest Kuronue went back after it and was pierced through the major arteries with bamboo spears, utterly ending his life.  While Kurama is now a member of the party of Yusuke.  A demon disguised as Kuronue attacks Kurama while he is alone.

All information found in the movie, Yu Yu Hakusho: Poltergeist Report.

Hikage is on a quest: to find out why his best friend Maoru had tried to kill him with a poisoned shuriken (ninja throwing star). The two were ninjas retained by the Takada clan during the "warring states" period in Japan, long before the rise of the Edo Shoganate. However, for some reason Marou had ran off, but not before trying to kill Hikage. The shuriken had missed his right eye, but Hikage was cut below it. Somehow, Hikage survived the poison.

Louise appears in Red Garden: Dead Girls among with her lover Edgar, she's apparently his younger sister, but actually she's probably as old as Dead Girls. Both come to a high school in New York. Louise is looking for Dead Girls and she wants to be friends with them, although she seems to not know what a real friendship is and that's not something gained easily. Louise is an android, that don't wand to be loved by Edgar, who isn't immortal as she is.

Section 2 Division 2 Team 1: Son of the head of Shinohara Heavy Industries, the company that makes 90% of the labors in the world. After a falling out with his father, Asuma joined the police force and specifically requested to be assigned to the labor units. Smart, honest to a fault, and sometimes a bit hot-headed, Asuma is a very good officer, although he's often used by Goto as a lackey. Noa and Hiromi's commanding officer in the field, he has a soft spot for the former. Goto recognizes Asuma has some talent in diverse fields, as can be seen in various places throughout the series.

Ash is easily distinguished by his mask: a grim reaper skull with its tongue sticking out. Ash joined the Chess Pieces in the hopes on using their immense power to conquer the world, ending all other wars countries might bring up, preventing the deaths of the children he loves. Ash's personality is rather unusual on Chess Piece standards, being both playful and fun-loving. Ash prefers to solve matters without fighting, urging the other knights during a meeting not to deal with Rapunzel's insolence. Phantom himself, who is one of the Knights' more sadistic members, states that he could never hate Ash, as he is "just that sort of person". Ash is almost always seen enjoyably playing with children, usually Defu, Ko, and Benni, three children he rescued from the war, when not fighting a battle. Ash is also very willing to take punishment, sometimes volunteering to be punished when he felt he did something wrong. Galian also states that Ash is usually not one to give up in battle. Ash's original design had little differences from his original one, the most notable being having a regular mask rather than a skull one.

Sio is a first-class foe: brilliant, mentally unbalanced, and vindictive as hell. But she wasn't always so nasty. The once sweet little girl was twisted by the pain of losing everyone she loved to Afro's blade. She's out for revenge, and she won't quit until Afro gets what he deserves. By her side is Jinno, also known as Kuma.

The female protagonist. She is a "Juuden-chan": someone from a world that is parallel to our own, capable of recharging people who are depressed or unlucky. She is however not very good at it and is a bit of an airhead. Because she has the ability to use phasing, she normally can't be seen by regular humans. This is done so she can do her job without causing distraction. She loves to watch a rather ecchi anime series called "Millie-chan". Whilst other Juden-chan focus on charging people and getting paid, Plug focuses on discovering the root of their problems so that they won't become depressed again. - Wikipedia

Hikage is on a quest: to find out why his best friend Maoru had tried to kill him with a poisoned shuriken (ninja throwing star). The two were ninjas retained by the Takada clan during the "warring states" period in Japan, long before the rise of the Edo Shoganate. However, for some reason Marou had ran off, but not before trying to kill Hikage. The shuriken had missed his right eye, but Hikage was cut below it. Somehow, Hikage survived the poison.

Louise appears in Red Garden: Dead Girls among with her lover Edgar, she's apparently his younger sister, but actually she's probably as old as Dead Girls. Both come to a high school in New York. Louise is looking for Dead Girls and she wants to be friends with them, although she seems to not know what a real friendship is and that's not something gained easily. Louise is an android, that don't wand to be loved by Edgar, who isn't immortal as she is.

Section 2 Division 2 Team 1: Son of the head of Shinohara Heavy Industries, the company that makes 90% of the labors in the world. After a falling out with his father, Asuma joined the police force and specifically requested to be assigned to the labor units. Smart, honest to a fault, and sometimes a bit hot-headed, Asuma is a very good officer, although he's often used by Goto as a lackey. Noa and Hiromi's commanding officer in the field, he has a soft spot for the former. Goto recognizes Asuma has some talent in diverse fields, as can be seen in various places throughout the series.

Ash is easily distinguished by his mask: a grim reaper skull with its tongue sticking out. Ash joined the Chess Pieces in the hopes on using their immense power to conquer the world, ending all other wars countries might bring up, preventing the deaths of the children he loves. Ash's personality is rather unusual on Chess Piece standards, being both playful and fun-loving. Ash prefers to solve matters without fighting, urging the other knights during a meeting not to deal with Rapunzel's insolence. Phantom himself, who is one of the Knights' more sadistic members, states that he could never hate Ash, as he is "just that sort of person". Ash is almost always seen enjoyably playing with children, usually Defu, Ko, and Benni, three children he rescued from the war, when not fighting a battle. Ash is also very willing to take punishment, sometimes volunteering to be punished when he felt he did something wrong. Galian also states that Ash is usually not one to give up in battle. Ash's original design had little differences from his original one, the most notable being having a regular mask rather than a skull one.

Sio is a first-class foe: brilliant, mentally unbalanced, and vindictive as hell. But she wasn't always so nasty. The once sweet little girl was twisted by the pain of losing everyone she loved to Afro's blade. She's out for revenge, and she won't quit until Afro gets what he deserves. By her side is Jinno, also known as Kuma.


In [15]:
# character_attributes_df = pd.json_normalize(df_characters['parsed_attributes_dict'])
# character_attributes_df['character_id'] = df_characters['character_id']

# print("First few rows of character_attributes_df:")
# display(character_attributes_df.head())

# print("Info of character_attributes_df:")
# character_attributes_df.info()

In [16]:
# character_attributes_df.to_csv('character_attributes_df.csv', index=False)
# print("df_anime has been saved to 'df_anime_processed.csv'")

In [17]:
from collections import Counter

# Collect all attribute keys from the parsed_attributes_dict column
all_keys = []
for attr_dict in df_characters['parsed_attributes_dict']:
    if isinstance(attr_dict, dict):
        all_keys.extend(attr_dict.keys())

# Count the frequency of each attribute key
key_counts = Counter(all_keys)

# Get the 10 most common attributes
top_attributes = key_counts.most_common(30)

print("Top 10 most used attributes:")
for attribute, count in top_attributes:
    print(f"{attribute}: {count}")

Top 10 most used attributes:
Age: 5919
Height: 5375
Birthday: 4594
Weight: 2775
Blood type: 1810
Blood Type: 1224
Episode: 914
Gender: 871
Likes: 768
Occupation: 725
Race: 622
Gender Identity: 604
Affiliation: 598
Dislikes: 567
Birthdate: 554
Debut: 528
Position: 468
Class: 427
Hobbies: 407
BWH: 310
Zodiac: 307
Eye Color: 305
Hair Color: 284
Birthplace: 264
Nationality: 253
Eye color: 252
(Source: 235
Species: 225
Hair color: 223
Horoscope: 221

In [18]:
# Function to clean attribute keys
def clean_attribute_key(key):
    """Clean attribute keys by removing special characters and normalizing case"""
    if not isinstance(key, str):
        return key
    # Remove leading/trailing whitespace and special characters like *
    cleaned = key.strip().lstrip('*(#-•➣・').strip()
    # Normalize to title case for consistency
    cleaned = cleaned.lower()
    return cleaned

# Apply cleaning to all parsed_attributes_dict
for index, row in df_characters.iterrows():
    attributes_dict = row['parsed_attributes_dict']
    
    if isinstance(attributes_dict, dict) and attributes_dict:
        # Create a new dictionary with cleaned keys
        cleaned_dict = {}
        for key, value in attributes_dict.items():
            cleaned_key = clean_attribute_key(key)
            # If the cleaned key already exists, keep the first occurrence
            if cleaned_key not in cleaned_dict:
                cleaned_dict[cleaned_key] = value
        
        # Update the dataframe with cleaned dictionary
        df_characters.at[index, 'parsed_attributes_dict'] = cleaned_dict

print("Attribute keys have been cleaned and normalized.")
print("\nRecounting attributes after cleaning:")

# Recount attributes with cleaned keys
all_keys_cleaned = []
for attr_dict in df_characters['parsed_attributes_dict']:
    if isinstance(attr_dict, dict):
        all_keys_cleaned.extend(attr_dict.keys())

key_counts_cleaned = Counter(all_keys_cleaned)
top_attributes_cleaned = key_counts_cleaned.most_common(20)

print("Top 30 most used attributes after cleaning:")
for attribute, count in top_attributes_cleaned:
    print(f"{attribute}: {count}")
    print(f"\n{attribute.upper()} (appears {count} times):")
    examples_found = 0
    for i, row in df_characters.iterrows():
        attr_dict = row['parsed_attributes_dict']
        if isinstance(attr_dict, dict) and attribute in attr_dict:
            print(f"  - {row['full_name']}: {attr_dict[attribute]}")
            examples_found += 1
            if examples_found >= 10:  # Show 3 examples per attribute
                break

Attribute keys have been cleaned and normalized.

Recounting attributes after cleaning:
Top 30 most used attributes after cleaning:
age: 5953

AGE (appears 5953 times):
  - Ichigo Kurosaki: 15 (beginning); 17 (currently)
  - Edward Elric: 15-16 (series), 18 (movie, end of the series)
  - Alphonse Elric: 14-15 (10 at the 2003 end, 13 at movie, 17 at the manga/fmab end)
  - Sasuke Uchiha: 12-13 (I); 16-17 (II); 19 (The Last: Naruto the Movie); 32 (Boruto: Naruto the Movie)
  - Itachi Uchiha: 17-18 (I); 21 (II)
  - Naruto Uzumaki: 12-13 (Naruto part I), 15-17 (part II), 19 (The Last: Naruto the Movie), 27 (Naruto epilogue), 32 (Boruto: Naruto the Movie)
  - Haruhi Fujioka: 16
  - Tamaki Suou: 17
  - Mitsukuni Haninozuka: 17
  - Takashi Morinozuka: 18
height: 5407

HEIGHT (appears 5407 times):
  - Spike Spiegel: 185 cm (6' 1")
  - Ichigo Kurosaki: 174->181 cm
  - Rukia Kuchiki: 144 cm (4' 8")
  - Orihime Inoue: 5'2" (157 cm)
  - Sasuke Uchiha: 153.2 cm(I); 168 cm (II); 175 cm (The Last: Naruto the Movie); 182 cm (Boruto: Naruto the Movie)
  - Itachi Uchiha: 175 cm (I); 178 cm (II)
  - Ippo Makunouchi: 164 cm (5'5")
  - Naruto Uzumaki: 145–147 cm (I), 166 cm (II), 174 cm (The Last: Naruto the Movie), 180 cm (Boruto: Naruto the Movie)
  - Haruhi Fujioka: 155 cm (5'1")
  - Tamaki Suou: 183 cm (6'0")
birthday: 4624

BIRTHDAY (appears 4624 times):
  - Faye Valentine: August 14, 1994
  - Ichigo Kurosaki: July 15 (Cancer)
  - Rukia Kuchiki: January 14 (Capricorn)
  - Orihime Inoue: September 3
  - Edward Elric: 1899
  - Sasuke Uchiha: July 23
  - Itachi Uchiha: June 9th (Gemini)
  - Naruto Uzumaki: October 10
  - Haruhi Fujioka: February 4
  - Tamaki Suou: April 8 (Aries)
blood type: 3060

BLOOD TYPE (appears 3060 times):
  - Spike Spiegel: O
  - Orihime Inoue: B
  - Sasuke Uchiha: AB
  - Itachi Uchiha: AB
  - Naruto Uzumaki: B
  - Haruhi Fujioka: O
  - Tamaki Suou: A
  - Mitsukuni Haninozuka: AB
  - Takashi Morinozuka: O
  - Hikaru Hitachiin: B
weight: 2802

WEIGHT (appears 2802 times):
  - Spike Spiegel: 70 kg (155 lbs)
  - Ichigo Kurosaki: 61->66 kg
  - Rukia Kuchiki: 33 kg (72.6 lb)
  - Orihime Inoue: 45 kg
  - Sasuke Uchiha: 43.5kg(I); 52.2kg (II); 55kg (The Last: Naruto the Movie); 65kg (Boruto: Naruto the Movie)
  - Itachi Uchiha: 57 kg (I); 58 kg (II)
  - Naruto Uzumaki: 41–44 kg (I), 52 kg (II), 56 kg (The Last: Naruto the Movie), 66 kg (Boruto: Naruto the Movie)
  - Killua Zoldyck: 45 kg
  - Kurapika: 59 kg
  - Leorio Paladiknight: 85 kg
episode: 915

EPISODE (appears 915 times):
  - Spike Spiegel: 185 cm (6' 1")
  - Ichigo Kurosaki: 174->181 cm
  - Rukia Kuchiki: 144 cm (4' 8")
  - Orihime Inoue: 5'2" (157 cm)
  - Sasuke Uchiha: 153.2 cm(I); 168 cm (II); 175 cm (The Last: Naruto the Movie); 182 cm (Boruto: Naruto the Movie)
  - Itachi Uchiha: 175 cm (I); 178 cm (II)
  - Ippo Makunouchi: 164 cm (5'5")
  - Naruto Uzumaki: 145–147 cm (I), 166 cm (II), 174 cm (The Last: Naruto the Movie), 180 cm (Boruto: Naruto the Movie)
  - Haruhi Fujioka: 155 cm (5'1")
  - Tamaki Suou: 183 cm (6'0")
birthday: 4624

BIRTHDAY (appears 4624 times):
  - Faye Valentine: August 14, 1994
  - Ichigo Kurosaki: July 15 (Cancer)
  - Rukia Kuchiki: January 14 (Capricorn)
  - Orihime Inoue: September 3
  - Edward Elric: 1899
  - Sasuke Uchiha: July 23
  - Itachi Uchiha: June 9th (Gemini)
  - Naruto Uzumaki: October 10
  - Haruhi Fujioka: February 4
  - Tamaki Suou: April 8 (Aries)
blood type: 3060

BLOOD TYPE (appears 3060 times):
  - Spike Spiegel: O
  - Orihime Inoue: B
  - Sasuke Uchiha: AB
  - Itachi Uchiha: AB
  - Naruto Uzumaki: B
  - Haruhi Fujioka: O
  - Tamaki Suou: A
  - Mitsukuni Haninozuka: AB
  - Takashi Morinozuka: O
  - Hikaru Hitachiin: B
weight: 2802

WEIGHT (appears 2802 times):
  - Spike Spiegel: 70 kg (155 lbs)
  - Ichigo Kurosaki: 61->66 kg
  - Rukia Kuchiki: 33 kg (72.6 lb)
  - Orihime Inoue: 45 kg
  - Sasuke Uchiha: 43.5kg(I); 52.2kg (II); 55kg (The Last: Naruto the Movie); 65kg (Boruto: Naruto the Movie)
  - Itachi Uchiha: 57 kg (I); 58 kg (II)
  - Naruto Uzumaki: 41–44 kg (I), 52 kg (II), 56 kg (The Last: Naruto the Movie), 66 kg (Boruto: Naruto the Movie)
  - Killua Zoldyck: 45 kg
  - Kurapika: 59 kg
  - Leorio Paladiknight: 85 kg
episode: 915

EPISODE (appears 915 times):
  - Iwato Kaze: 124
  - Hiroshi Akimoto: 143
  - Junya Tokitsu: 479
  - Kanae Ishida: 640-641
  - Iwato Kaze: 124
  - Hiroshi Akimoto: 143
  - Junya Tokitsu: 479
  - Kanae Ishida: 640-641
  - Ryuusuke Higo: 765-766, 822-823, 925
  - Detective Kosugi: 720-721
  - Ryuusuke Higo: 765-766, 822-823, 925
  - Detective Kosugi: 720-721
  - Teruko Akaiwa: 790
  - Kouzou Adachi: 802
  - Adachi Ryouta: 63
  - Tooru Aida: 179
gender: 881

GENDER (appears 881 times):
  - Ippo Makunouchi: Male
  - Kurapika: Male
  - Leorio Paladiknight: Male
  - Ovan: Male
  - Haseo: Male
  - Shino: Female
  - Tabby: Female
  - Phyllo: Male
  - Sakisaka: Male
  - Kuroudo Akabane: male
likes: 769

LIKES (appears 769 times):
  - Train Heartnet: Milk, Seafood, Rice balls (onigiri)
  - Rinslet Walker: money, jewelery, handsome men, cute girls, etc.
  - L Lawliet: sweets
  - Ryuk: apples, the human world, chaos, Misa
  - Light Yagami: Justice
  - Kakashi Hatake: Icha-Icha series, Broiled Saury with salt, Miso soup with eggplant
  - Yuu Kanda: Soba, Tempura (pumpkin, green peppers, and lotus root)
  - Komui Lee: Coffee (Blue Mountain), Lenalee
  - Sakura Haruno: Syrup coated anko dumplings; Umeboshi; Anmitsu; Word Puzzles; Studying her medical studdies.
  - Kyou Souma: codfish, his karate master, and Tooru
occupation: 726

OCCUPATION (appears 726 times):
  - Rukia Kuchiki: Shinigami in the 13th Division,  Lieutenant of Squad 13, Captain of Squad 13 (end)
  - Edward Elric: State Alchemist
  - Alphonse Elric: Alchemist
  - Ippo Makunouchi: Professional Boxer; Makunouchi Fishing Boat
  - Killua Zoldyck: Assassin (Formerly), Hunter
  - Leorio Paladiknight: Hunter, Medical Student
  - Gon Freecss: Hunter
  - Hisoka Morow: Hunter,  Phantom Troupe's #4 (former)
  - Train Heartnet: Sweeper
  - Rinslet Walker: thief-for-hire
race: 626

RACE (appears 626 times):
  - Ichigo Kurosaki: Human Quincy, Hollow
  - Gokuu Son: Saiyan
  - Karin Maaka: Unvampire (anime), Spring of Psyche (manga)
  - Alucard: True Vampire
  - Alexander Anderson: Human/Regenerator (later turned into the "Monster of God" when fused with Helena's nail)Age: unknown, physically appears to be in his 40-50s
  - Seras Victoria: Vampire, Human (Formerly)
  - Yumiko Takagi: Human
  - Heinkel Wolfe: Human/Regenerator (Cyborg)
  - Bulma: Earthling
  - Sunako Nakahara: Human
gender identity: 604

GENDER IDENTITY (appears 604 times):
  - Teruko Akaiwa: 790
  - Kouzou Adachi: 802
  - Adachi Ryouta: 63
  - Tooru Aida: 179
gender: 881

GENDER (appears 881 times):
  - Ippo Makunouchi: Male
  - Kurapika: Male
  - Leorio Paladiknight: Male
  - Ovan: Male
  - Haseo: Male
  - Shino: Female
  - Tabby: Female
  - Phyllo: Male
  - Sakisaka: Male
  - Kuroudo Akabane: male
likes: 769

LIKES (appears 769 times):
  - Train Heartnet: Milk, Seafood, Rice balls (onigiri)
  - Rinslet Walker: money, jewelery, handsome men, cute girls, etc.
  - L Lawliet: sweets
  - Ryuk: apples, the human world, chaos, Misa
  - Light Yagami: Justice
  - Kakashi Hatake: Icha-Icha series, Broiled Saury with salt, Miso soup with eggplant
  - Yuu Kanda: Soba, Tempura (pumpkin, green peppers, and lotus root)
  - Komui Lee: Coffee (Blue Mountain), Lenalee
  - Sakura Haruno: Syrup coated anko dumplings; Umeboshi; Anmitsu; Word Puzzles; Studying her medical studdies.
  - Kyou Souma: codfish, his karate master, and Tooru
occupation: 726

OCCUPATION (appears 726 times):
  - Rukia Kuchiki: Shinigami in the 13th Division,  Lieutenant of Squad 13, Captain of Squad 13 (end)
  - Edward Elric: State Alchemist
  - Alphonse Elric: Alchemist
  - Ippo Makunouchi: Professional Boxer; Makunouchi Fishing Boat
  - Killua Zoldyck: Assassin (Formerly), Hunter
  - Leorio Paladiknight: Hunter, Medical Student
  - Gon Freecss: Hunter
  - Hisoka Morow: Hunter,  Phantom Troupe's #4 (former)
  - Train Heartnet: Sweeper
  - Rinslet Walker: thief-for-hire
race: 626

RACE (appears 626 times):
  - Ichigo Kurosaki: Human Quincy, Hollow
  - Gokuu Son: Saiyan
  - Karin Maaka: Unvampire (anime), Spring of Psyche (manga)
  - Alucard: True Vampire
  - Alexander Anderson: Human/Regenerator (later turned into the "Monster of God" when fused with Helena's nail)Age: unknown, physically appears to be in his 40-50s
  - Seras Victoria: Vampire, Human (Formerly)
  - Yumiko Takagi: Human
  - Heinkel Wolfe: Human/Regenerator (Cyborg)
  - Bulma: Earthling
  - Sunako Nakahara: Human
gender identity: 604

GENDER IDENTITY (appears 604 times):
  - Kanae Ishida: Female
  - Kanae Ishida: Female
  - Detective Kosugi: Male
  - Detective Kosugi: Male
  - Teruko Akaiwa: female
  - Kouzou Adachi: male
  - Tooru Aida: male
  - Ryouzen Adachi: male
  - Shingo Aihara: male
  - Etsuko Aikawa: female
  - Yousuke Akagi: male
  - Kengo Akahoshi: male
affiliation: 599

AFFILIATION (appears 599 times):
  - Itachi Uchiha: Akatsuki
  - Luffy Monkey D.: Straw Hat Pirates
  - Robin Nico: Straw Hat Pirates; Baroque Works (former)
  - Zoro Roronoa: Straw Hat Pirates
  - Franky: Straw Hat Pirates; Franky Family (former); Tom's Workers (former)
  - Trowa Barton: The Gundam Pilots
  - Tetsunosuke Ichimura: Shinsengumi
  - Souji Okita: Shinsengumi
  - Sanosuke Harada: Shinsengumi
  - Sanji: Straw Hat Pirates; Baratie (former)
dislikes: 567

DISLIKES (appears 567 times):
  - Train Heartnet: Woman's Tears
  - Rinslet Walker: ghosts, narcissists, etc
  - L Lawliet: Wearing socks
  - Ryuk: being bored, not having apples, relapse
  - Light Yagami: Evil
  - Kakashi Hatake: Anything sweet
  - Yuu Kanda: Anything group related and lots more
  - Komui Lee: Tidying up, Lenalee's future husband.
  - Sakura Haruno: Anything Spicy; Naruto (at first); Ino (at first)
  - Kyou Souma: chives, leeks, onions, miso, rain, water, Yuki
eye color: 561

EYE COLOR (appears 561 times):
  - Killua Zoldyck: Blue
  - Kurapika: blue (1999); brown (manga & 2011); scarlet (when angered)
  - Leorio Paladiknight: Green (1999), Brown (2011)
  - Gon Freecss: Brown
  - Hisoka Morow: blue (1999), yellow (2011)
  - Illumi Zoldyck: Black
  - Chrollo Lucilfer: Black (1999), Grey (2011)
  - Light Yagami: Brown
  - Trowa Barton: Dark green
  - Quatre Raberba Winner: Blue
birthdate: 554

BIRTHDATE (appears 554 times):
  - Teruko Akaiwa: female
  - Kouzou Adachi: male
  - Tooru Aida: male
  - Ryouzen Adachi: male
  - Shingo Aihara: male
  - Etsuko Aikawa: female
  - Yousuke Akagi: male
  - Kengo Akahoshi: male
affiliation: 599

AFFILIATION (appears 599 times):
  - Itachi Uchiha: Akatsuki
  - Luffy Monkey D.: Straw Hat Pirates
  - Robin Nico: Straw Hat Pirates; Baroque Works (former)
  - Zoro Roronoa: Straw Hat Pirates
  - Franky: Straw Hat Pirates; Franky Family (former); Tom's Workers (former)
  - Trowa Barton: The Gundam Pilots
  - Tetsunosuke Ichimura: Shinsengumi
  - Souji Okita: Shinsengumi
  - Sanosuke Harada: Shinsengumi
  - Sanji: Straw Hat Pirates; Baratie (former)
dislikes: 567

DISLIKES (appears 567 times):
  - Train Heartnet: Woman's Tears
  - Rinslet Walker: ghosts, narcissists, etc
  - L Lawliet: Wearing socks
  - Ryuk: being bored, not having apples, relapse
  - Light Yagami: Evil
  - Kakashi Hatake: Anything sweet
  - Yuu Kanda: Anything group related and lots more
  - Komui Lee: Tidying up, Lenalee's future husband.
  - Sakura Haruno: Anything Spicy; Naruto (at first); Ino (at first)
  - Kyou Souma: chives, leeks, onions, miso, rain, water, Yuki
eye color: 561

EYE COLOR (appears 561 times):
  - Killua Zoldyck: Blue
  - Kurapika: blue (1999); brown (manga & 2011); scarlet (when angered)
  - Leorio Paladiknight: Green (1999), Brown (2011)
  - Gon Freecss: Brown
  - Hisoka Morow: blue (1999), yellow (2011)
  - Illumi Zoldyck: Black
  - Chrollo Lucilfer: Black (1999), Grey (2011)
  - Light Yagami: Brown
  - Trowa Barton: Dark green
  - Quatre Raberba Winner: Blue
birthdate: 554

BIRTHDATE (appears 554 times):
  - Spike Spiegel: June 26, 2044
  - Luffy Monkey D.: May 5, Taurus
  - Robin Nico: February 6, Aquarius
  - Zoro Roronoa: November 11, Scorpio
  - Franky: March 9
  - Light Yagami: February 28, 1986 (1989 in the anime)
  - Asuka Langley Souryuu: December 4, 2001
  - Shia: September 3
  - Yuu Kanda: June 6
  - Yakumo Tsukamoto: March 23
debut: 528

DEBUT (appears 528 times):
  - Matsunosuke Shibui: Episode 1 "Tempestuous Temperaments"
  - Tomonoshin Shibui: Episode 1 "Tempestuous Temperaments"
  - Sousuke Kawara: Episode 3 "Hellhounds for Hire" (part 1)
  - Heitarou Kawara: Episode 3 "Hellhounds for Hire" (part 1)
  - Moronobu Hishikawa: Episode 5 "Artistic Anarchy"
  - Isaac Kitching: Episode 6 "Stranger Searching"
  - Shinsuke: Episode 7 "A Risky Racket"
  - Bunta Ogura: Episode 8 "The Art of Altercation"
  - Budoukiba: Episode 8 "The Art of Altercation"
  - Spike Spiegel: June 26, 2044
  - Luffy Monkey D.: May 5, Taurus
  - Robin Nico: February 6, Aquarius
  - Zoro Roronoa: November 11, Scorpio
  - Franky: March 9
  - Light Yagami: February 28, 1986 (1989 in the anime)
  - Asuka Langley Souryuu: December 4, 2001
  - Shia: September 3
  - Yuu Kanda: June 6
  - Yakumo Tsukamoto: March 23
debut: 528

DEBUT (appears 528 times):
  - Matsunosuke Shibui: Episode 1 "Tempestuous Temperaments"
  - Tomonoshin Shibui: Episode 1 "Tempestuous Temperaments"
  - Sousuke Kawara: Episode 3 "Hellhounds for Hire" (part 1)
  - Heitarou Kawara: Episode 3 "Hellhounds for Hire" (part 1)
  - Moronobu Hishikawa: Episode 5 "Artistic Anarchy"
  - Isaac Kitching: Episode 6 "Stranger Searching"
  - Shinsuke: Episode 7 "A Risky Racket"
  - Bunta Ogura: Episode 8 "The Art of Altercation"
  - Budoukiba: Episode 8 "The Art of Altercation"
  - Shino: Episode 11 "Gamblers and Gallantry"
hair color: 509

HAIR COLOR (appears 509 times):
  - Kurapika: blonde
  - Leorio Paladiknight: Brown (1999), Black (2011)
  - Hisoka Morow: 1999 anime - blue (Hunter Exam arc), red (Heavens Arena arc); red (2011)
  - Illumi Zoldyck: Black
  - Chrollo Lucilfer: Black
  - Light Yagami: Brown
  - Trowa Barton: Brown
  - Quatre Raberba Winner: Platinum gold
  - Wufei Chang: Black
  - Yuu Kanda: Dark Blue, Black
position: 490

POSITION (appears 490 times):
  - Luffy Monkey D.: Captain
  - Robin Nico: Archaeologist
  - Zoro Roronoa: Swordsman
  - Franky: Shipwright
  - Toshizou Hijikata: Second-in-command
  - Sanosuke Harada: 10th Unit Captain
  - Sanji: Cook
  - Chopper Tony Tony: Doctor
  - Hanamichi Sakuragi: Power Forward
  - Kaede Rukawa: Small Forward, SF
class: 451

CLASS (appears 451 times):
  - Ovan: Steam Gunner
  - Haseo: Adept Rogue (MultiWeapon in Japanese)
  - Shino: Harvest Cleric
  - Tabby: Tribal Grappler
  - Phyllo: Harvest Cleric
  - Sakisaka: Steam Gunner
  - Subaru: Heavy axeman
  - Kaede Rukawa: 1
  - Ryouta Miyagi: 1
  - Nagomi Yashi: 1-B
hobbies: 407

HOBBIES (appears 407 times):
  - Sven Vollfied: Being well groomed, polishing cars
  - Rinslet Walker: disguises, shopping, tarrot card reading
  - Louise Françoise Le Blanc de La Vallière: knitting
  - Saito Hiraga: The Internet
  - Sousuke Sagara: Fishing, Reading
  - Azusa Hinomori: Fashion
  - Sanzou Genjou: Not many. He does read the newspaper though.
  - Gokuu Son: Eating, fighting, being with Sanzou
  - Hakkai Cho: Drinking
  - Gojou Sha: Smoking, playing card games, flirting with women, picking on Goku
  - Shino: Episode 11 "Gamblers and Gallantry"
hair color: 509

HAIR COLOR (appears 509 times):
  - Kurapika: blonde
  - Leorio Paladiknight: Brown (1999), Black (2011)
  - Hisoka Morow: 1999 anime - blue (Hunter Exam arc), red (Heavens Arena arc); red (2011)
  - Illumi Zoldyck: Black
  - Chrollo Lucilfer: Black
  - Light Yagami: Brown
  - Trowa Barton: Brown
  - Quatre Raberba Winner: Platinum gold
  - Wufei Chang: Black
  - Yuu Kanda: Dark Blue, Black
position: 490

POSITION (appears 490 times):
  - Luffy Monkey D.: Captain
  - Robin Nico: Archaeologist
  - Zoro Roronoa: Swordsman
  - Franky: Shipwright
  - Toshizou Hijikata: Second-in-command
  - Sanosuke Harada: 10th Unit Captain
  - Sanji: Cook
  - Chopper Tony Tony: Doctor
  - Hanamichi Sakuragi: Power Forward
  - Kaede Rukawa: Small Forward, SF
class: 451

CLASS (appears 451 times):
  - Ovan: Steam Gunner
  - Haseo: Adept Rogue (MultiWeapon in Japanese)
  - Shino: Harvest Cleric
  - Tabby: Tribal Grappler
  - Phyllo: Harvest Cleric
  - Sakisaka: Steam Gunner
  - Subaru: Heavy axeman
  - Kaede Rukawa: 1
  - Ryouta Miyagi: 1
  - Nagomi Yashi: 1-B
hobbies: 407

HOBBIES (appears 407 times):
  - Sven Vollfied: Being well groomed, polishing cars
  - Rinslet Walker: disguises, shopping, tarrot card reading
  - Louise Françoise Le Blanc de La Vallière: knitting
  - Saito Hiraga: The Internet
  - Sousuke Sagara: Fishing, Reading
  - Azusa Hinomori: Fashion
  - Sanzou Genjou: Not many. He does read the newspaper though.
  - Gokuu Son: Eating, fighting, being with Sanzou
  - Hakkai Cho: Drinking
  - Gojou Sha: Smoking, playing card games, flirting with women, picking on Goku

In [19]:
top_attributes_cleaned

[('age', 5953),
 ('height', 5407),
 ('birthday', 4624),
 ('blood type', 3060),
 ('weight', 2802),
 ('episode', 915),
 ('gender', 881),
 ('likes', 769),
 ('occupation', 726),
 ('race', 626),
 ('gender identity', 604),
 ('affiliation', 599),
 ('dislikes', 567),
 ('eye color', 561),
 ('birthdate', 554),
 ('debut', 528),
 ('hair color', 509),
 ('position', 490),
 ('class', 451),
 ('hobbies', 407)]

In [31]:
# Create a new dataframe with character_id and top attributes as columns
# Define the attributes we want to extract based on the top attributes
top_attribute_keys = [attr for attr, count in top_attributes_cleaned]

# Function to convert attribute names to snake_case
def to_snake_case(text):
    """Convert text to snake_case"""
    if not isinstance(text, str):
        return text
    # Replace spaces and hyphens with underscores
    snake = text.replace(' ', '_').replace('-', '_')
    # Remove any special characters except underscores
    snake = ''.join(c if c.isalnum() or c == '_' else '' for c in snake)
    # Replace multiple underscores with single underscore
    while '__' in snake:
        snake = snake.replace('__', '_')
    # Remove leading/trailing underscores
    snake = snake.strip('_')
    return snake.lower()

# Initialize a list to store the data
character_attributes_data = []

for index, row in df_characters.iterrows():
    character_id = row['character_id']
    attributes_dict = row['parsed_attributes_dict']
    
    # Create a dictionary for this character with character_id and all top attributes
    char_data = {'character_id': character_id}
    
    # Add each top attribute as a column with snake_case name
    if isinstance(attributes_dict, dict):
        for attr_key in top_attribute_keys:
            snake_case_key = to_snake_case(attr_key)
            char_data[snake_case_key] = attributes_dict.get(attr_key, None)
    else:
        for attr_key in top_attribute_keys:
            snake_case_key = to_snake_case(attr_key)
            char_data[snake_case_key] = None
    
    character_attributes_data.append(char_data)

# Create the dataframe
df_character_attributes = pd.DataFrame(character_attributes_data)

print(f"Created dataframe with {len(df_character_attributes)} characters and {len(df_character_attributes.columns)} columns")
print(f"\nColumns: {list(df_character_attributes.columns)}")
print(f"\nFirst few rows:")
display(df_character_attributes.head(10))

# Show some statistics
print(f"\nNon-null counts for each attribute:")
print(df_character_attributes.count())

Created dataframe with 139497 characters and 21 columns

Columns: ['character_id', 'age', 'height', 'birthday', 'blood_type', 'weight', 'episode', 'gender', 'likes', 'occupation', 'race', 'gender_identity', 'affiliation', 'dislikes', 'eye_color', 'birthdate', 'debut', 'hair_color', 'position', 'class', 'hobbies']

First few rows:

,character_id,age,height,birthday,blood_type,weight,episode,gender,likes,occupation,...,gender_identity,affiliation,dislikes,eye_color,birthdate,debut,hair_color,position,class,hobbies
0,1,None,"185 cm (6' 1"")",None,O,70 kg (155 lbs),None,None,None,None,...,None,None,None,None,"June 26, 2044",None,None,None,None,None
1,2,None,None,"August 14, 1994",None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,3,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,4,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,5,15 (beginning); 17 (currently),174->181 cm,July 15 (Cancer),None,61->66 kg,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,6,None,"144 cm (4' 8"")",January 14 (Capricorn),None,33 kg (72.6 lb),None,None,None,"Shinigami in the 13th Division, Lieutenant of...",...,None,None,None,None,None,None,None,None,None,None
6,7,None,"5'2"" (157 cm)",September 3,B,45 kg,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,11,"15-16 (series), 18 (movie, end of the series)",None,1899,None,None,None,None,None,State Alchemist,...,None,None,None,None,None,None,None,None,None,None
8,12,"14-15 (10 at the 2003 end, 13 at movie, 17 at ...",None,None,None,None,None,None,None,Alchemist,...,None,None,None,None,None,None,None,None,None,None
9,13,12-13 (I); 16-17 (II); 19 (The Last: Naruto th...,153.2 cm(I); 168 cm (II); 175 cm (The Last: Na...,July 23,AB,43.5kg(I); 52.2kg (II); 55kg (The Last: Naruto...,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

Non-null counts for each attribute:
character_id       139497
age                  5953
height               5407
birthday             4624
blood_type           3060
weight               2802
episode               915
gender                881
likes                 769
occupation            726
race                  626
gender_identity       604
affiliation           599
dislikes              567
eye_color             561
birthdate             554
debut                 528
hair_color            509
position              490
class                 451
hobbies               407
dtype: int64

In [33]:
# Drop rows where all attribute columns are null (keeping only character_id)
attribute_columns = [col for col in df_character_attributes.columns if col != 'character_id']
df_character_attributes = df_character_attributes.dropna(subset=attribute_columns, how='all')

print(f"After dropping characters with no attributes: {len(df_character_attributes)} characters remaining")
display(df_character_attributes.head(10))

After dropping characters with no attributes: 10734 characters remaining

,character_id,age,height,birthday,blood_type,weight,episode,gender,likes,occupation,...,gender_identity,affiliation,dislikes,eye_color,birthdate,debut,hair_color,position,class,hobbies
0,1,None,"185 cm (6' 1"")",None,O,70 kg (155 lbs),None,None,None,None,...,None,None,None,None,"June 26, 2044",None,None,None,None,None
1,2,None,None,"August 14, 1994",None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,5,15 (beginning); 17 (currently),174->181 cm,July 15 (Cancer),None,61->66 kg,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,6,None,"144 cm (4' 8"")",January 14 (Capricorn),None,33 kg (72.6 lb),None,None,None,"Shinigami in the 13th Division, Lieutenant of...",...,None,None,None,None,None,None,None,None,None,None
6,7,None,"5'2"" (157 cm)",September 3,B,45 kg,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,11,"15-16 (series), 18 (movie, end of the series)",None,1899,None,None,None,None,None,State Alchemist,...,None,None,None,None,None,None,None,None,None,None
8,12,"14-15 (10 at the 2003 end, 13 at movie, 17 at ...",None,None,None,None,None,None,None,Alchemist,...,None,None,None,None,None,None,None,None,None,None
9,13,12-13 (I); 16-17 (II); 19 (The Last: Naruto th...,153.2 cm(I); 168 cm (II); 175 cm (The Last: Na...,July 23,AB,43.5kg(I); 52.2kg (II); 55kg (The Last: Naruto...,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
10,14,17-18 (I); 21 (II),175 cm (I); 178 cm (II),June 9th (Gemini),AB,57 kg (I); 58 kg (II),None,None,None,None,...,None,Akatsuki,None,None,None,None,None,None,None,None
11,15,None,"164 cm (5'5"")",None,None,None,None,Male,None,Professional Boxer; Makunouchi Fishing Boat,...,None,None,None,None,None,None,None,None,None,None

In [34]:
# Compare gender and gender_identity columns
if 'gender' in df_character_attributes.columns and 'gender_identity' in df_character_attributes.columns:
    # Count different scenarios
    both_same = 0
    both_different = 0
    gender_has_value_identity_none = 0
    gender_none_identity_has_value = 0
    both_none = 0
    
    for index, row in df_character_attributes.iterrows():
        gender = row['gender']
        gender_identity = row['gender_identity']
        
        # Both are None
        if pd.isna(gender) and pd.isna(gender_identity):
            both_none += 1
        # Both have values
        elif pd.notna(gender) and pd.notna(gender_identity):
            if gender == gender_identity:
                both_same += 1
            else:
                both_different += 1
        # Only gender has value
        elif pd.notna(gender) and pd.isna(gender_identity):
            gender_has_value_identity_none += 1
        # Only gender_identity has value
        elif pd.isna(gender) and pd.notna(gender_identity):
            gender_none_identity_has_value += 1
    
    print("=== Comparison between 'gender' and 'gender_identity' ===\n")
    print(f"Both have same value: {both_same}")
    print(f"Both have values but different: {both_different}")
    print(f"Only 'gender' has value (gender_identity is None): {gender_has_value_identity_none}")
    print(f"Only 'gender_identity' has value (gender is None): {gender_none_identity_has_value}")
    print(f"Both are None: {both_none}")
    print(f"\nTotal: {both_same + both_different + gender_has_value_identity_none + gender_none_identity_has_value + both_none}")
    
    # Show examples of different values
    if both_different > 0:
        print("\n=== Examples where both have values but are different ===")
        count = 0
        for index, row in df_character_attributes.iterrows():
            if pd.notna(row['gender']) and pd.notna(row['gender_identity']) and row['gender'] != row['gender_identity']:
                char_id = row['character_id']
                char_name = df_characters[df_characters['character_id'] == char_id]['full_name'].values[0] if len(df_characters[df_characters['character_id'] == char_id]) > 0 else 'Unknown'
                print(f"  - {char_name}: gender='{row['gender']}', gender_identity='{row['gender_identity']}'")
                count += 1
                if count >= 10:
                    break
else:
    print("One or both columns ('gender', 'gender_identity') do not exist in the dataframe")
    print(f"Available columns: {list(df_character_attributes.columns)}")

=== Comparison between 'gender' and 'gender_identity' ===

Both have same value: 0
Both have values but different: 0
Only 'gender' has value (gender_identity is None): 881
Only 'gender_identity' has value (gender is None): 604
Both are None: 9249

Total: 10734

In [35]:
# Combine gender_identity into gender column
# If gender is None but gender_identity has a value, use gender_identity
if 'gender' in df_character_attributes.columns and 'gender_identity' in df_character_attributes.columns:
    for index, row in df_character_attributes.iterrows():
        if pd.isna(row['gender']) and pd.notna(row['gender_identity']):
            df_character_attributes.at[index, 'gender'] = row['gender_identity']
    
    # Drop the gender_identity column since we've merged it into gender
    df_character_attributes = df_character_attributes.drop(columns=['gender_identity'])
    
    print("Successfully combined 'gender_identity' into 'gender' column")
    print(f"Dropped 'gender_identity' column")
    print(f"\nUpdated columns: {list(df_character_attributes.columns)}")
    print(f"\nGender column non-null count: {df_character_attributes['gender'].notna().sum()}")
else:
    print("One or both columns do not exist")

Successfully combined 'gender_identity' into 'gender' column
Dropped 'gender_identity' column

Updated columns: ['character_id', 'age', 'height', 'birthday', 'blood_type', 'weight', 'episode', 'gender', 'likes', 'occupation', 'race', 'affiliation', 'dislikes', 'eye_color', 'birthdate', 'debut', 'hair_color', 'position', 'class', 'hobbies']

Gender column non-null count: 1485

In [36]:
# Show unique values of gender column
if 'gender' in df_character_attributes.columns:
    unique_genders = df_character_attributes['gender'].unique()
    gender_counts = df_character_attributes['gender'].value_counts(dropna=False)
    
    print(f"Unique gender values: {len(unique_genders)}")
    print(f"\nUnique values:")
    for gender in unique_genders:
        print(f"  - {gender}")
    
    print(f"\nValue counts:")
    print(gender_counts)
else:
    print("'gender' column does not exist in the dataframe")

Unique gender values: 25

Unique values:
  - None
  - Male
  - Female
  - male
  - female
  - male  (can change to female)
  - F
  - Female (brought up as male)
  - None
  - Unknown
  - Male (Normal)/Female (Kämpfer)
  - FEMALE
  - Feminine
  - Bird
  - Genderless
  - Male(+Female)
  - unknown
  - Possesses the ability to switch between a male or female body at will.
  - Male (Half-Demon)
  - Female (Purebred Demon (Devil))
  - Female (Succubus)
  - Female (Demi-beastfolk)
  - Female (Dragonfolk)
  - Intersex
  - Non-Binary

Value counts:
gender
None                                                                      9249
Male                                                                       876
Female                                                                     531
male                                                                        38
female                                                                      14
Intersex                                                                     5
Unknown                                                                      2
Non-Binary                                                                   2
None                                                                         1
Possesses the ability to switch between a male or female body at will.       1
male  (can change to female)                                                 1
Female (Dragonfolk)                                                          1
Female (Demi-beastfolk)                                                      1
Female (Succubus)                                                            1
Female (Purebred Demon (Devil))                                              1
Male (Half-Demon)                                                            1
unknown                                                                      1
Female (brought up as male)                                                  1
Male(+Female)                                                                1
Genderless                                                                   1
Bird                                                                         1
F                                                                            1
FEMALE                                                                       1
Male (Normal)/Female (Kämpfer)                                               1
Feminine                                                                     1
Name: count, dtype: int64

In [37]:
# Clean gender column - normalize to 'Male' and 'Female'
if 'gender' in df_character_attributes.columns:
    # Create a mapping for normalization
    def normalize_gender(gender_value):
        if pd.isna(gender_value):
            return gender_value
        
        gender_str = str(gender_value).strip().lower()
        
        # Normalize female variants
        if gender_str in ['female', 'f']:
            return 'Female'
        # Normalize male variants
        elif gender_str in ['male', 'm']:
            return 'Male'
        # Keep other values as-is for now
        else:
            return gender_value
    
    # Apply normalization
    df_character_attributes['gender'] = df_character_attributes['gender'].apply(normalize_gender)
    
    print("Gender column has been normalized")
    print(f"\nUpdated gender value counts:")
    print(df_character_attributes['gender'].value_counts(dropna=False))
    
    # Find characters with gender values other than 'Male' or 'Female'
    other_genders = df_character_attributes[
        (df_character_attributes['gender'].notna()) & 
        (~df_character_attributes['gender'].isin(['Male', 'Female']))
    ]
    
    if len(other_genders) > 0:
        print(f"\n=== Characters with gender other than 'Male' or 'Female': {len(other_genders)} ===")
        for index, row in other_genders.iterrows():
            char_id = row['character_id']
            gender = row['gender']
            char_name = df_characters[df_characters['character_id'] == char_id]['full_name'].values[0] if len(df_characters[df_characters['character_id'] == char_id]) > 0 else 'Unknown'
            print(f"  Character ID: {char_id}, Name: {char_name}, Gender: '{gender}'")
    else:
        print("\nAll characters have gender values of 'Male', 'Female', or None")
else:
    print("'gender' column does not exist in the dataframe")

Gender column has been normalized

Updated gender value counts:
gender
None                                                                      9249
Male                                                                       914
Female                                                                     547
Intersex                                                                     5
Unknown                                                                      2
Non-Binary                                                                   2
None                                                                         1
Male (Normal)/Female (Kämpfer)                                               1
Feminine                                                                     1
Bird                                                                         1
Female (brought up as male)                                                  1
Male(+Female)                                                                1
unknown                                                                      1
Possesses the ability to switch between a male or female body at will.       1
Male (Half-Demon)                                                            1
Female (Purebred Demon (Devil))                                              1
Female (Succubus)                                                            1
Female (Demi-beastfolk)                                                      1
Female (Dragonfolk)                                                          1
male  (can change to female)                                                 1
Genderless                                                                   1
Name: count, dtype: int64

=== Characters with gender other than 'Male' or 'Female': 24 ===
  Character ID: 601, Name: Alucard, Gender: 'male  (can change to female)'
  Character ID: 6110, Name: Kyuubei Yagyuu, Gender: 'Female (brought up as male)'
  Character ID: 11354, Name: Ribbons Almark, Gender: 'None'
  Character ID: 12300, Name: Neferpitou, Gender: 'Unknown'
  Character ID: 24977, Name: Natsuru Senou, Gender: 'Male (Normal)/Female (Kämpfer)'
  Character ID: 76812, Name: Treeya, Gender: 'Feminine'
  Character ID: 134200, Name: Subterraneans, Gender: 'Unknown'
  Character ID: 139954, Name: Tsubasa Akai, Gender: 'Bird'
  Character ID: 154965, Name: Yuzuha, Gender: 'Genderless'
  Character ID: 185552, Name: Pavel, Gender: 'Male(+Female)'
  Character ID: 189223, Name: Uraume, Gender: 'unknown'
  Character ID: 197422, Name: Guy Crimson, Gender: 'Possesses the ability to switch between a male or female body at will.'
  Character ID: 201684, Name: Melnes, Gender: 'Male (Half-Demon)'
  Character ID: 202817, Name: Echidna, Gender: 'Female (Purebred Demon (Devil))'
  Character ID: 202818, Name: Steina, Gender: 'Female (Succubus)'
  Character ID: 202819, Name: Lili, Gender: 'Female (Demi-beastfolk)'
  Character ID: 206857, Name: Jerietta, Gender: 'Female (Dragonfolk)'
  Character ID: 217582, Name: Tarao, Gender: 'Intersex'
  Character ID: 224608, Name: Kuku, Gender: 'Intersex'
  Character ID: 230956, Name: Ooma Takezuka, Gender: 'Intersex'
  Character ID: 231651, Name: Michika Takezuka, Gender: 'Intersex'
  Character ID: 253331, Name: Momoika, Gender: 'Intersex'
  Character ID: 260256, Name: Setsu, Gender: 'Non-Binary'
  Character ID: 267991, Name: Racio, Gender: 'Non-Binary'

In [38]:
df_character_attributes.to_csv('character_attributes_cleaned.csv', index=False)

In [39]:
# Check what columns we actually have in df_character_attributes
print("Available columns in df_character_attributes:")
print(list(df_character_attributes.columns))
print(f"\nTotal columns: {len(df_character_attributes.columns)}")

Available columns in df_character_attributes:
['character_id', 'age', 'height', 'birthday', 'blood_type', 'weight', 'episode', 'gender', 'likes', 'occupation', 'race', 'affiliation', 'dislikes', 'eye_color', 'birthdate', 'debut', 'hair_color', 'position', 'class', 'hobbies']

Total columns: 20

In [40]:
%pip install neo4j python-dotenv

Requirement already satisfied: neo4j in /Users/estergracia/miniconda3/lib/python3.9/site-packages (5.28.2)
Requirement already satisfied: python-dotenv in /Users/estergracia/miniconda3/lib/python3.9/site-packages (1.2.1)
Requirement already satisfied: pytz in /Users/estergracia/miniconda3/lib/python3.9/site-packages (from neo4j) (2024.2)
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

In [43]:
from neo4j import GraphDatabase
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
USER = os.getenv("NEO4J_USER", "neo4j")
PASSWORD = os.getenv("NEO4J_PASSWORD", "your_password")

def get_driver():
    return GraphDatabase.driver(URI, auth=(USER, PASSWORD))

# Function to update character attributes in Neo4j
def update_character_attributes_batch(driver, data_batch, attribute_columns):
    if not data_batch:
        return
    
    # Build the SET clause dynamically based on available attributes
    # Convert snake_case to camelCase for Neo4j properties
    def snake_to_camel(snake_str):
        components = snake_str.split('_')
        return components[0] + ''.join(x.title() for x in components[1:])
    
    # Build SET statements for each attribute
    set_statements = []
    for col in attribute_columns:
        camel_case_col = snake_to_camel(col)
        set_statements.append(f"c.{camel_case_col} = row.{col}")
    
    set_clause = ',\n        '.join(set_statements)
    
    cypher_query = f"""
    UNWIND $batch AS row
    MATCH (c:Character {{malCharacterId: row.character_id}})
    SET {set_clause}
    """
    
    with driver.session() as session:
        session.run(cypher_query, batch=data_batch)

print("Neo4j connection setup complete")

Neo4j connection setup complete

In [44]:
# Prepare data for Neo4j ingestion
# Convert dataframe to list of dictionaries, converting NaN to None
character_data_for_neo4j = []

# Get all attribute columns (exclude character_id)
attribute_cols = [col for col in df_character_attributes.columns if col != 'character_id']

for index, row in df_character_attributes.iterrows():
    char_dict = {'character_id': int(row['character_id'])}
    
    # Dynamically add all attribute columns
    for col in attribute_cols:
        char_dict[col] = row[col] if pd.notna(row[col]) else None
    
    character_data_for_neo4j.append(char_dict)

print(f"Prepared {len(character_data_for_neo4j)} character records for Neo4j ingestion")
print(f"Attributes to be updated: {attribute_cols}")
print(f"\nFirst record example:")
print(character_data_for_neo4j[0])

Prepared 10734 character records for Neo4j ingestion
Attributes to be updated: ['age', 'height', 'birthday', 'blood_type', 'weight', 'episode', 'gender', 'likes', 'occupation', 'race', 'affiliation', 'dislikes', 'eye_color', 'birthdate', 'debut', 'hair_color', 'position', 'class', 'hobbies']

First record example:
{'character_id': 1, 'age': None, 'height': '185 cm (6\' 1")', 'birthday': None, 'blood_type': 'O', 'weight': '70 kg (155 lbs)', 'episode': None, 'gender': None, 'likes': None, 'occupation': None, 'race': None, 'affiliation': None, 'dislikes': None, 'eye_color': None, 'birthdate': 'June 26, 2044', 'debut': None, 'hair_color': None, 'position': None, 'class': None, 'hobbies': None}

In [46]:
# Ingest character attributes to Neo4j
def main():
    driver = get_driver()
    
    # Get attribute columns (exclude character_id)
    attribute_cols = [col for col in df_character_attributes.columns if col != 'character_id']
    
    print("Starting character attributes ingestion to Neo4j...")
    print(f"Attributes to update: {', '.join(attribute_cols)}")
    
    total = len(character_data_for_neo4j)
    BATCH_SIZE = 500  # Process in batches of 500
    
    for i in range(0, total, BATCH_SIZE):
        batch = character_data_for_neo4j[i : i + BATCH_SIZE]
        
        # Update Neo4j
        update_character_attributes_batch(driver, batch, attribute_cols)
        
        print(f"Progress: {min(i + BATCH_SIZE, total)}/{total} characters processed...")
    
    print("\n✅ Character attributes ingestion complete!")
    driver.close()

# Run the ingestion
main()

Starting character attributes ingestion to Neo4j...
Attributes to update: age, height, birthday, blood_type, weight, episode, gender, likes, occupation, race, affiliation, dislikes, eye_color, birthdate, debut, hair_color, position, class, hobbies
Progress: 500/10734 characters processed...
Progress: 500/10734 characters processed...
Progress: 1000/10734 characters processed...
Progress: 1000/10734 characters processed...
Progress: 1500/10734 characters processed...
Progress: 1500/10734 characters processed...
Progress: 2000/10734 characters processed...
Progress: 2000/10734 characters processed...
Progress: 2500/10734 characters processed...
Progress: 2500/10734 characters processed...
Progress: 3000/10734 characters processed...
Progress: 3000/10734 characters processed...
Progress: 3500/10734 characters processed...
Progress: 3500/10734 characters processed...
Progress: 4000/10734 characters processed...
Progress: 4000/10734 characters processed...
Progress: 4500/10734 characters processed...
Progress: 4500/10734 characters processed...
Progress: 5000/10734 characters processed...
Progress: 5000/10734 characters processed...
Progress: 5500/10734 characters processed...
Progress: 5500/10734 characters processed...
Progress: 6000/10734 characters processed...
Progress: 6000/10734 characters processed...
Progress: 6500/10734 characters processed...
Progress: 6500/10734 characters processed...
Progress: 7000/10734 characters processed...
Progress: 7000/10734 characters processed...
Progress: 7500/10734 characters processed...
Progress: 7500/10734 characters processed...
Progress: 8000/10734 characters processed...
Progress: 8000/10734 characters processed...
Progress: 8500/10734 characters processed...
Progress: 8500/10734 characters processed...
Progress: 9000/10734 characters processed...
Progress: 9000/10734 characters processed...
Progress: 9500/10734 characters processed...
Progress: 9500/10734 characters processed...
Progress: 10000/10734 characters processed...
Progress: 10000/10734 characters processed...
Progress: 10500/10734 characters processed...
Progress: 10500/10734 characters processed...
Progress: 10734/10734 characters processed...

✅ Character attributes ingestion complete!
Progress: 10734/10734 characters processed...

✅ Character attributes ingestion complete!